name: "Test Workflow"
on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/action.yaml
  pull_request:
    paths:
      - '*'
      - .github/workflows/eks.yaml
permissions:
  id-token: write # This is requird for aws oidc connection
  contents: read # This is required for actions/checkout
  pull-requests: write # This is required for gh bot to comment PR
  
jobs:
  jobs:
  step1:
    -name: generate-secret
      run: | 
        secret=`echo $RANDOM`
        echo "::add-mask::${secret}"
        echo "secret=$secret" >> $GITHUB_OUTPUT
    -name: print-secret-via-another-step
      run: |
        echo "::add-mask::${SECRET_OUTPUTS}"
        echo "generated secret is : ${SECRET_OUTPUTS}"
      env:
        SECRET_OUTPUTS="${{ steps.step1.outputs.secret }}"
  outputs:
    secret: ${{ steps.step1.outputs.secret }} 
