# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
    paths:
      - .github/workflows/new.yaml
  pull_request:
    branches: [ "main" ]
    paths:
      - .github/workflows/new.yaml
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  printing-secret:
    runs-on: ubuntu-latest
    outputs:
     secret: ${{ steps.generate.outputs.secret }} 
    steps:
    - name: generate
      id: generate
      run: | 
        secret=`echo $RANDOM`
        echo "::add-mask::$secret"
        echo "secret=$secret" >> $GITHUB_OUTPUT
    - name: print face
      run: |
        echo "generated secret is : ${SECRET}"
      env:
        SECRET: ${{ steps.generate.outputs.secret }}
  fetch-secret:
    runs-on: ubuntu-latest
    needs: [printing-secret]
    steps:
    - name: fetch
      shell: bash
      run: |
        secret="${{ needs.printing-secret.outputs.secret }}"
        echo "print secret : ${secret}"
