# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  printing-number:
    runs-on: ubuntu-latest
    steps:
    - name: generate
      id: generate
      run: | 
        number=`echo $RANDOM`
        echo "number=$number" >> $GITHUB_OUTPUT
    - name: print
      run: |
        echo "generated number is : ${NUMBER}"
      env:
        NUMBER: ${{ steps.generate.outputs.number }}
    outputs:
     number: ${{ steps.generate.outputs.number }} 
  fetch-number:
    runs-on: ubuntu-latest
    needs: [printing-number]
    steps:
    - name: fetch
      id: fetch
      run: |
        echo "${{ needs.printing-numbers.outputs.number }}"
        echo "fetched number is : ${FETCHED_SECRET}"
      env:
        FETCHED_SECRET: ${{ needs.printing-number.outputs.number }}
